### ISSUE TITLE
Initial todo

### ISSUE THREAD

**Issue by bix0r** [bix0r/moya-console#1]
Búa til console app fyrir moya.

Verður aðskilið sjálfri moya, sér Github project.

Nota sirka svona:
```moya mysql:mycli```
og maður er kominn inn í mycli fyrir moya vef. Vefurinn er fundinn út frá current directory, þannig að það er nóg að vera einhvernstaðar innan vefs, og gaurinn finnur út base.

Punktar:
- [ ] Finna base path út frá current
- [ ] Hægt að setja param sem segir hvaða moya
- [ ] Gert með Symfony console gaurnum (eins og composer t.d.)
- [ ] Hægt að setja user based conf í ~/.moyarc
- [ ] Væri magnað að þetta mundi virka á eldri útgáfur en NG

Aðgerðir/Commands:
- [x] **mysql::client** bara inn í mysql clientinn sjálfann. Fínt fyrir import t.d.
- [ ] **mysql::mycli** mycli client
- [ ] **mysql::conf** sýnir user + pass
- [x] **mysql::exec** keyra eina línu af sql
- [ ] **mysql::dump** keyrir svipað og mydump í dag
- [x] **mysql::restore** keyra inn skrá. Sýnist mér vera of erfitt að fá ` < dump.sql` til að virka
- [ ] **mysql::init** keyrir inn initial sql fyrir vef
- [ ] **mysql::upgrade** væri geðveikt að geta keyrt þetta til að uppfæra sql á vef, en þetta má bíða
- [ ] **mysql::create** býr til nýjan grunn út frá conf (mCreate í dag)
- [ ] **phpstorm::init** býr til .idea möppu og græjar það sem við getum búið til þarna inn
- [ ] **phpstorm::update** uppfæra .idea möppu ef hægt er
- [ ] **cache::clean** hreinsa allt cache. Hægt að velja hvaða cache með param
- [ ] **perms:fix** laga réttindi
- [ ] **webserver:create** býr til nginx/apache config fyrir vefinn (nginxCreate í dag)
- [ ] **module:create** býr til nýja einingu. Hægt að stilla slatta með params
